name: Build Dataflow flex template. 
description: Build and upload a dataflow flex template.
author: Johan Hansson, Niklas Hansson
inputs:
  GOOGLE_APPLICATION_CREDENTIALS:
    description: The path to the decoded google credentials
    required: true
  IMAGE_TAG: 
    description: The image tag for the docker image on gcloud container registry. 
    required: true
  DOCKERIMAGE_PATH: 
    description: The path to the docker image which will contain the dataflow job. 
    required: true
  TEMPLATE_PATH: 
    description: The bucket and the path where the built. 
    required: true
  METADATA_PATH: 
    description: The metadata file path. 
    required: true
  GCP_PROJECT:
    description: The GCP project
    required: true
outputs:
  WORKFLOW_URL:
    description: Link to the built job. 
branding:
  color: 'purple'
  icon: 'upload-cloud'
runs:
  using: 'docker'
  image: 'Dockerfile'
