name: Dataflow flex template example
on:
  push:
    branches:
      - develop
      - master 


jobs:
  build-flex-template:
    name: Build the Dataflow flex template
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build step
        env:
          IMAGE_NAME: samples/dataflow/streaming-beam  
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GKE_KEY }}
          GITHUB_SHA: 112232
        id: kubeflow
        uses: JohanWork/action-dataflow-template@master
        with:
          GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GKE_KEY}}
          IMAGE_TAG:  gcr.io/${{ secrets.GCP_PROJECT }}/${{env.IMAGE_NAME}}:${{env.GITHUB_SHA}}
          DOCKERIMAGE_PATH: example/.
          TEMPLATE_PATH: gs://${{ secrets.GCP_BUCKET }}/dataflow/templates/streaming-beam.json
          METADATA_PATH: example/metadata.json
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

