name: Dataflow flex template example
on:
  push:
    branches:
      - develop
      - master 


jobs:
  build-preprocessing:
    name: Build the preprocessing image
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build Dataflow flex template
        env:
          IMAGE_NAME: samples/dataflow/streaming-beam  
          BUCKET_NAME: ${{ secrets.GCP_BUCKET }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GKE_KEY }}
          GITHUB_SHA: $GITHUB_SHA
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        id: kubeflow
        uses: JohanWork/action-dataflow-template@master
        with:
          GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GKE_KEY}}
          IMAGE_TAG:  gcr.io/${{ env.GCP_PROJECT }}/${{env.IMAGE_NAME}}:${{env.GITHUB_SHA}}
          DOCKERIMAGE_PATH: example/.
          TEMPLATE_PATH: gs://${{env.BUCKET_NAME}}/dataflow/templates/streaming-beam.json
          METADATA_PATH: example/metadata.json
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

